import fs from 'fs';
import path from 'path';
import { glob } from 'glob';

const SRC_DIR = path.resolve('res/storylines');

console.log('Building storylines...');

const allData: Record<string, Record<string, Record<string, string>>> = {};

// Find all storyline markdown files
const files = glob.sync(path.join(SRC_DIR, 'storylines*.md'));

if (files.length === 0) {
    console.warn('No storyline files found in ' + SRC_DIR);
}

files.forEach(file => {
    const filename = path.basename(file);
    let locale = filename.match(/storylines_([a-z]{2})\.md$/)?.[1];

    if (!locale && filename === 'storylines.md') {
        locale = 'en';
    }

    if (!locale) {
        console.warn(`Skipping ${filename}: Could not determine locale`);
        return;
    }

    console.log(`Processing ${filename} (${locale})...`);
    const content = fs.readFileSync(file, 'utf-8');
    const data = parseMarkdown(content);

    allData[locale] = data;
});

// Generate TypeScript Content
const tsContent = `/**
 * Auto-generated by scripts/build-storylines.ts
 * Do not edit manually.
 */

const DATA: Record<string, Record<string, Record<string, string>>> = ${JSON.stringify(allData, null, 4)};

export function getStoryline(galaxyId: string, planetId: string, locale: string = 'en'): string | null {
    const galaxy = DATA[locale]?.[galaxyId] || DATA['en']?.[galaxyId];
    if (!galaxy) return null;
    return galaxy[planetId] || null;
}
`;

// Ensure output directory
const TS_OUT_FILE = path.resolve('src-generated/storylines/storylines.ts');
const TS_OUT_DIR = path.dirname(TS_OUT_FILE);

if (!fs.existsSync(TS_OUT_DIR)) {
    fs.mkdirSync(TS_OUT_DIR, { recursive: true });
}

fs.writeFileSync(TS_OUT_FILE, tsContent, 'utf-8');
console.log(`Saved compiled storylines to ${TS_OUT_FILE}`);


/**
 * Parses markdown content into a nested map structure:
 * {
 *   "galaxy-id": {
 *     "planet-id": "Text content..."
 *   }
 * }
 */
function parseMarkdown(markdown: string): Record<string, Record<string, string>> {
    const lines = markdown.split('\n');
    const result: Record<string, Record<string, string>> = {};

    let currentGalaxyId: string | null = null;
    let currentPlanetId: string | null = null;
    let currentTextLines: string[] = [];

    const saveCurrentText = () => {
        if (currentGalaxyId && currentPlanetId && currentTextLines.length > 0) {
            if (!result[currentGalaxyId]) {
                result[currentGalaxyId] = {};
            }
            // Join lines and trim extra whitespace
            const text = currentTextLines.join('\n').trim();
            if (text) {
                result[currentGalaxyId][currentPlanetId] = text;
            }
        }
        currentTextLines = [];
    };

    for (const line of lines) {
        const trimmed = line.trim();

        // Check for Galaxy Header (e.g., "## galaxy-id")
        if (trimmed.startsWith('## ')) {
            saveCurrentText();
            currentGalaxyId = trimmed.substring(3).trim();
            currentPlanetId = null;
        }
        // Check for Planet Header (e.g., "### planet-id")
        else if (trimmed.startsWith('### ')) {
            saveCurrentText();
            currentPlanetId = trimmed.substring(4).trim();
        }
        // Content lines
        else if (currentGalaxyId && currentPlanetId) {
            // Include empty lines if we have started collecting text, to preserve paragraph breaks
            // But skip leading empty lines of a block
            if (currentTextLines.length > 0 || trimmed !== '') {
                currentTextLines.push(line);
            }
        }
    }
    // Save last block
    saveCurrentText();

    return result;
}
